### ISSUE TITLE
Implement a "Quiet Update Check" setting

### ISSUE THREAD

**Issue by matchai** [dfrankland/hyper-sync-settings#11]
I'd like to suggest the implementation of a "Quiet Update Check" setting, as [sync-settings](https://github.com/atom-community/sync-settings) has implemented. This toggle would allow users to hide the "Your settings are up to date" notification.

![image](https://cloud.githubusercontent.com/assets/4658208/18554202/72a9174c-7b31-11e6-8175-f5b831334744.png)

I would've gone ahead and made a PR but I was curious whether you'd suggest including this boolean setting in `.hyperterm.js` or in the config file, since it's already being written in.

**Comment by dfrankland** [comment]
Better inside the `~/hyperterm.js`, no? That way you can backup and restore that setting 👍
