### ISSUE TITLE
Seems to not work with Hyper 0.8.1

### ISSUE THREAD

**Issue by RobbieTheWagner** [dfrankland/hyper-sync-settings#14]
Unsure what the error is. I cannot read the full alert that pops up to find out where the logs are.

**Comment by RobbieTheWagner** [comment]
Seems to be the nodegit issue still, even though I am not on Sierra yet.

**Comment by dfrankland** [comment]
I'm sorry, I wish there were a better `git` bindings for node ;(

**Comment by RobbieTheWagner** [comment]
@dfrankland why would this be an issue if I hadn't updated to Sierra though?
