### ISSUE TITLE
'HyperTerm' --> 'Hyper' breaks the plugin

### ISSUE THREAD

**Issue by Net-Geek** [dfrankland/hyper-sync-settings#15]
HyperTerm has now been renamed to Hyper. This leads to the syncing functionality no longer working due to references to the plugin dir in which has now also changed.

**Comment by dfrankland** [comment]
@Net-Geek, thank you for your work 👍 helped out a lot. ~~I've got a [PR on Hyper that will fix the `nodegit` dependency](https://github.com/zeit/hyper/pull/970) then we can release!~~ Never mind, we can [release right away](https://www.npmjs.com/package/hyper-sync-settings) 😄
