### ISSUE TITLE
Cannot open HyperTerm with this package installed

### ISSUE THREAD

**Issue by benadamstyles** [dfrankland/hyper-sync-settings#2]
HyperTerm v0.6.0

Installing this package (i.e. putting it in the `plugins` array in `~/.hyperterm.js`) makes it so that HyperTerm immediately crashes on opening, reliably every time. I have the requisite `syncSettings` in `~/.hyperterm.js` and have set up the private gist. Let me know if there's any more information I can give.

**Comment by dfrankland** [comment]
This is a known issue, please see here https://github.com/dfrankland/hyperterm-sync-settings/issues/1

I'll be adding a quick hack today to fix that and try to add the proper fix to `hyperterm` itself as well.

In the mean time you may either clone this repo directly to `~/.hyperterm_plugins/local`,  run `npm install`, and add it to you local plugins in `~/.hyperterm.js` or go the location where the plugin installed already `~/.hyperterm_plugins/node_modules/hyperterm-sync-settings/`, create a file called `.npmrc` with these contents:

```
runtime = electron
target = 1.2.5
disturl = https://atom.io/download/atom-shell
```

Then delete `~/.hyperterm_plugins/node_modules/hyperterm-sync-settings/node_modules`, and finally run `npm install` in `~/.hyperterm_plugins/node_modules/hyperterm-sync-settings/`.

**Comment by benadamstyles** [comment]
Ah ok thanks, I saw that issue but didn't realise it was the cause of this. I'll leave this open for now in case other people come with the same problem, and close it when you've pushed the fix. Thanks for the quick and detailed response!

**Comment by dfrankland** [comment]
This [pull request to `hyperterm`](https://github.com/zeit/hyperterm/pull/291) should fix the issue! :)

**Comment by dfrankland** [comment]
Fixed!
