### ISSUE TITLE
Fix `nodegit` or migrate to something else

### ISSUE THREAD

**Issue by dfrankland** [dfrankland/hyper-sync-settings#20]
The `nodegit` package has difficulty installing (#1, #2, #4, #10, #14, #17, #18, #19) which makes for a bad user experience, it would be best to do one of the following:

1.  Package a prebuilt electron version of `nodegit` with `hyper-sync-settings` so there's no need to install from `npm`.

2.  Use another `npm` package that uses Github's API directly

3.  Spawn `child_process`es using the installed `git` CLI

Does anyone else have any better ideas or solutions?

**Comment by birkhofflee** [comment]
I'll be following on this. This plugin is likely very useful to me, and I can't even install it, so I'll try after you fixed this!

**Comment by dfrankland** [comment]
So I did some digging and the pre-built binaries for `nodegit` just don't exist for the newest versions of electron, cross-platform. Because of this `nodegit` will try to build from source which leads to more problems... This will be difficult to solve unfortunately.

**Comment by dfrankland** [comment]
The newest prebuilt that works is:
*   https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-electron-v1.4-darwin-x64.tar.gz
*   https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-electron-v1.4-win32-x64.tar.gz
*   **There is currently no `linux` build...**

The newest prebuilt that works for all 3 main platforms is:
*   https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.15.1-electron-v1.2-darwin-x64.tar.gz
*   https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.15.1-electron-v1.2-linux-x64.tar.gz
*   https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.15.1-electron-v1.2-win32-x64.tar.gz

>   For reference you can test finding prebuilts using this command:
>
>   ```bash
>   curl -I https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-electron-v1.4-{darwin,win32,linux}-x64.tar.gz
>   ```
>
>   This should return a `200` status.

**Comment by dfrankland** [comment]
This should be all fixed by `hyper-sync-settings@2.0.0` with PR https://github.com/dfrankland/hyper-sync-settings/pull/23
