### ISSUE TITLE
Improve the setup guide

### ISSUE THREAD

**Issue by Wikstahl** [dfrankland/hyper-sync-settings#208]
I don't have `.hyper-sync-settings.json` by default. Is this expected? What should the code that I put into `.hyper-sync-settings.json` look like?

**Comment by PranavARC** [comment]
Hey, so what you need to do is manually create that file in .hyper_plugins and have its contents be this:
```
{
  "personalAccessToken": "<INSERT YOUR PERSONAL ACCESS TOKEN>",
  "gistId": "<INSERT YOUR GISTID>"
}
```
Also make sure you name your gist (file) .hyper.js so it doesn't need to create another file.

**Comment by Wikstahl** [comment]
Thanks to your help I got it to work! I think this information should be added to the setup instructions.
