### ISSUE TITLE
ElementaryOS and other linux distros compatibility

### ISSUE THREAD

**Issue by letops** [dfrankland/hyper-sync-settings#21]
I know this is a pain, but I haven't been able to use this project for one simple reason:
ElementaryOS (and some other Linux distros), remove the contextual menu from all applications. This includes Hyperterminal, and it is the reason of why I cannot even execute a `Plugins > Sync Settings > Backup Settings`.

To improve compatibility with this kind of distros, I would recommend to create commands inside the terminal like: `Cmd + Shift + B` to execute a backup. This might help to only a small percentage of the users, but it would be greatly appreciated by all of them. (I am also raising an issue in the Wingpanel's and ElementaryOS' repos to request an alternative to display the contextual menu)

**Comment by dfrankland** [comment]
Totally understand. We should definitely make this user configurable. There are so many plug ins for Hyper that often there are conflicts with hot keys.

**Comment by dfrankland** [comment]
This should now work in `hyper-sync-settings@2.0.1`. Check out more details here: https://github.com/dfrankland/hyper-sync-settings#configsyncsettingsaccelerators
