### ISSUE TITLE
Feature request: Sync additional files

### ISSUE THREAD

**Issue by weedgrease** [dfrankland/hyper-sync-settings#25]
I would really appriciate this plugin allowing an array of additional files to upload to Gists on GitHub. Ideally the array would support globs. This would be helpful syncing fish terminal files, etc. What do you think? Hopefully I can help get a PR going!

**Comment by dfrankland** [comment]
Well, in reality the settings file that gets synced is a git repo. All you need to do is copy the other files or somehow link them, then  `git add` them and they'll keep synced.

**Comment by dfrankland** [comment]
Closing for now, feel free to open up if there's any additional comments.
