### ISSUE TITLE
Cant install: Cannot find module 'babel-runtime/helpers/toCumsumableArray

### ISSUE THREAD

**Issue by 0xAVX** [dfrankland/hyper-sync-settings#27]
This error is appear when update hyper to version 1.3.0

**Comment by victorloux** [comment]
See #24, it's been fixed by the latest commit (0bf81f01cfb59b3fa3cb3af42a74b16de790fe64) but hasn't been released yet.

In the meantime the quick fix is to:
- `cd ~/.hyper_plugins/node_modules/hyper-sync-settings/`
- `npm install babel-runtime`
- restart Hyper

**Comment by 0xAVX** [comment]
Thank you! Now it works
