### ISSUE TITLE
Error: can't not use simple-git in a directory that does not exist

### ISSUE THREAD

**Issue by SidKwok** [dfrankland/hyper-sync-settings#28]
hyper: 1.3.0
hyper-sync-settings: 2.0.1

**Comment by dfrankland** [comment]
Can you provide more details on how to reproduce this? I am not sure how you ran into this error.

**Comment by SidKwok** [comment]
I did what the guide tell me to do: create new gist(public), create new token, and input them in a .json file. But when I `Backup Settings`, the settings will not be uploaded and sometimes it will inform me with the error message above.

**Comment by dfrankland** [comment]
Gotcha, let me see if I can recreate that.

**Comment by dfrankland** [comment]
What OS are you running? Seems to work just fine for me on Ubuntu. I'll have to check macOS tomorrow.

**Comment by SidKwok** [comment]
macOs 10.12.3

**Comment by ghost** [comment]
i am having the exact same issue on macos 10.12.6. Is there any update to the issue?

**Comment by dfrankland** [comment]
Try updating to latest to fix this.
