### ISSUE TITLE
No backup / restore on Hyper 1.3.1

### ISSUE THREAD

**Issue by withinfocus** [dfrankland/hyper-sync-settings#29]
Running the latest release for Hyper, v1.3.1. Even with the fix from #27 to allow install, the menu options for backup and restore are not pushing notifications nor actually making any gist file changes.

**Comment by dfrankland** [comment]
With `hyper-sync-settings@2.0.2` everything should work again, do you mind updating and reporting back?

**Comment by withinfocus** [comment]
There we go. Took an uninstall / reinstall but good to go. Thanks.
