### ISSUE TITLE
Storing token in settings file that gets backed up?

### ISSUE THREAD

**Issue by ryanseys** [dfrankland/hyper-sync-settings#3]
So wait, you're storing the token used to access your Gists in a file that then gets backed up to Gist? You really shouldn't store any credentials anywhere other than on your local machine or in your brain. 

Perhaps add a setting to get the gist token from an environment variable instead of having to store it in the file being backed up?

**Comment by dfrankland** [comment]
You bring up a very valid point. Storing the token in an environmental variable would be one way to do this and I have no problem including that, but I wish there was a better way.

It'd be nice to be able to strip out the token when storing the config to Github and add it back when it gets restored...

**Comment by dfrankland** [comment]
I think the best solution is probably to generate another config file for `hyperterm-sync-settings` that is seperate from `~/.hyperterm.js`. This plugin already backs up the `~/.hyperterm.js` file to `~/.hyperterm_plugins` so I think the file should be kept as `~/.hyperterm_plugins/.hyperterm-sync-settings.js`. Here a user could specify to use `process.env.HYPERTERM_SYNC_SETTINGS_PERSONAL_ACCESS_TOKEN` or enter the token as a string.

**Comment by dfrankland** [comment]
Should be fixed now with this commit: https://github.com/dfrankland/hyperterm-sync-settings/commit/29d5a85ba0a3c206314a79bc8cf6c992f348ef8d. Docs are updated too!

**Comment by ryanseys** [comment]
👍  Awesome!
