### ISSUE TITLE
Hey sorry, total newbie question

### ISSUE THREAD

**Issue by jcklpe** [dfrankland/hyper-sync-settings#33]
Hey sorry, this is a totally newbie question. I'm a designer expanding my skillset with code but maybe I'm misunderstanding some stuff in the instructions. 

I try to add 'syncSettings' in my hyperterm settings under plugins: []

But when I do it doesn't seem to do anything. I haven't set up the gist or github toke etc. But I expected some kind of change, like it would create the sync settings folder in the .hyper-plugsin folder or something, but so far nothing. Doesn't show up in plugins menu either. 

I imagine I'm missing something really simple and fundamental but I'm not entirely clear on the process for this otherwise.

**Comment by dfrankland** [comment]
Not a problem! 👍 Always glad to help someone who's trying to expand their skills.

You'll need to complete the setup to get everything to load and show up in the menu as well.

**Comment by jcklpe** [comment]
Cool I'll give it a shot a report back. Thanks!

**Comment by dfrankland** [comment]
Closing for now, feel free to open if there's still a problem.
