### ISSUE TITLE
Latest version crash hyperterm

### ISSUE THREAD

**Issue by siygle** [dfrankland/hyper-sync-settings#4]
hyperterm: 0.6.0
hyperterm-sync-settings: 1.5.0

hyperteam will crash after turn on sync settings plugin (HyperTerm quit unexpectedly). After trace the code, I think NodeGit did not compatible with Node.js v6.

Just run the same demo of [nodegit](https://github.com/nodegit/nodegit#cloning-a-repository-and-reading-a-file) and it show up error under node v6

> Error: Module version mismatch. Expected 48, got 46.

**Comment by dfrankland** [comment]
Hey there! This module will not compile properly unless you are using HyperTerm on the `master` branch. This is the commit that fixes `hyperterm-sync-settings` https://github.com/zeit/hyperterm/pull/291

Everything should work when HyperTerm is released next.

Alternatively copy the [`.npmrc`](https://github.com/dfrankland/hyperterm-sync-settings/blob/master/.npmrc) file from this repo to `~/.hyperterm_plugins/node_modules/hyperterm-sync-settings` and then run `npm i -f` inside that folder.

**Comment by siygle** [comment]
Just try to upgrade to latest 0.7 and try again, but it appear another error:
![image](https://cloud.githubusercontent.com/assets/173408/17147323/d92008ce-5394-11e6-8326-d00f058f7ef8.png)

Also clean hyperterm_plugin and rebuild again but still get the same error. Seem nodegit did not build success after upgrade to 0.7.

ps: Sorry I'm not sure the root cause, if it's not related I'll move to hyperterm repo, you can close this issue. Thanks for your help. :)

**Comment by dfrankland** [comment]
Everything looks good you are now hitting this issue though https://github.com/dfrankland/hyperterm-sync-settings/issues/5

Since your issue is no longer related to hyperterm version 0.6.0 please go to https://github.com/dfrankland/hyperterm-sync-settings/issues/5 for any further issues.
