### ISSUE TITLE
Does not work with Hyper v3 Stable

### ISSUE THREAD

**Issue by FatehAK** [dfrankland/hyper-sync-settings#41]
Extension does not work with the latest stable release of Hyper v3. It is possibly due to the change in the config file location from `%UserProfile%\.hyper.js` to `%AppData%\Hyper\.hyper.js`. Could you update the extension to reflect this change?

**Comment by dfrankland** [comment]
Should be fixed now with `2.0.5`. Would you mind updating and reporting back?

**Comment by FatehAK** [comment]
It is able to sync correctly but the extension is generating an error in dev tools ->
`TypeError: Cannot read property 'getPath' of undefined
at Object.<anonymous> (C:\Users\ZZ\AppData\Roaming\Hyper\.hyper_plugins\node_modules\hyper-sync-settings\dist\constants.js:22)
at Object.<anonymous> (C:\Users\ZZ\AppData\Roaming\Hyper\.hyper_plugins\node_modules\hyper-sync-settings\dist\constants.js:38)`

**Comment by yahsieh** [comment]
`import { app } from 'electron'` at [constants.js#L1](https://github.com/dfrankland/hyper-sync-settings/blob/master/src/constants.js#L1) become undefined after app launched somehow, so maybe use [platform-folders]( https://www.npmjs.com/package/platform-folders) instead?

**Comment by kiraitachi** [comment]
I managed to get this fixed on a fresh install under 3.0 but with my other computers that already had Hyper installed and upgraded to 3.0 it doesnt work at all. 

Tried deleting config files, making symlynks between config files in `%UserProfile%\.hyper.j`s to `%AppData%\Hyper\.hyper.js` and reinstalling Hyper-sync-settings with no avail.

Is there any way to fix this plz¿?

**Comment by rfgamaral** [comment]
Yes, I broke it with #40 but I'm not sure why...

**Comment by kiraitachi** [comment]
> Yes, I broke it with #40 but I'm not sure why...

Hi @rfgamaral 

I'm sure your busy and stuff. But do we have any kind of ETA on when is this going to be fixed?

Everytime I open Hyper message with Hyper-sync-settings failed to load or backup settings appear and is killing me.

I miss this tool a lot for my Work Laptop to be Synced with my Personal Laptop.

Is there any way we might help?

Thanks in advance for your effort and time developing this tool.

Cheers

**Comment by rfgamaral** [comment]
I haven't fixed this because I'm not sure how and I don't have much time to investigate the problem right now. If someone knows where exactly is the problem I can open a new PR to fix it (but we'd still need @dfrankland to accept it and release a new version).

For now I recommend you disable this extension, that's what I did. Previous version doesn't work with Hyper v3 so even if you revert to an older version, it won't work with Hyper v3. This really needs to be fixed so we can use it again.

**Comment by TristanCottam** [comment]
Any updates ?

**Comment by dfrankland** [comment]
Could you try the new `hyper-sync-settings@3.0.1`?

**Comment by rfgamaral** [comment]
@dfrankland I can't find any changes from `3.0.0` to `3.0.1`. What have you changed between these versions that might have fixed this issue?

**Comment by dfrankland** [comment]
`3.0.0` to `3.0.1` was a small change to the `package.json`, just for publishing. The real update was the changes from `2.x.x` to `3.0.0`: https://github.com/dfrankland/hyper-sync-settings/pull/44

**Comment by rfgamaral** [comment]
Ah, ok, didn't notice there was a big change like that. Personally, the extension still doesn't work for me, I still get this error: https://github.com/dfrankland/hyper-sync-settings/issues/41#issuecomment-491327480
