### ISSUE TITLE
dose not work on hyper 3.0.2

### ISSUE THREAD

**Issue by sinlov** [dfrankland/hyper-sync-settings#43]
- env

```sh
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
$ hyper version
3.0.2
$ hyper list
hyperline
hyper-confirm
hyper-sync-settings
```

- github token is right
- gist `File name including extension.. ` in put .hyper.js
- file `~/.hyper_plugins/.hyper-sync-settings.json` set right

but when I use `Plugins > Sync Settings > Backup Settings`

- not push to my github gist 
- do not show any error!
- local .hyper.js file is right
```sh
$ file ~/.hyper_plugins/.hyper-sync-settings/.hyper.js
~/.hyper_plugins/.hyper-sync-settings/.hyper.js: UTF-8 Unicode text
```

**Comment by dfrankland** [comment]
Could you try the new `hyper-sync-settings@3.0.1`?

**Comment by filipesabella** [comment]
Also not working here.

I created a new gist and updated the config, when I click in `backup settings`, it shows the successful notification but it doesn't write anything to gist.github.
It also doesn't print anything to the developer console.

I'm on version 3.0.2.

**Comment by filipesabella** [comment]
A little more troubleshooting, I generated a new token, and even with the success message being displayed, the token shows as "never used" on github.

**Comment by NVFP4** [comment]
I have been facing the same issue.

After debugging the compiled js it looks like the `const hyperApp= electron.app;` is undefined which is equivalent to [this](https://github.com/dfrankland/hyper-sync-settings/blob/master/src/lib/checkForMissingSettings.ts#L12) or [this line of code](https://github.com/dfrankland/hyper-sync-settings/blob/406e354580dfea013f64e76be8d91b4d9a37b22a/src/constants.ts#L14)

Hence, the menu callbacks in `decorateMenu` are never exported, and clicking them has no effect.
